# ================================
# ArgoCD Application YAML (argocd-app.yaml)
# ================================

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fastapi-app
  namespace: argocd
spec:
  destination:
    namespace: fastapi-helm
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/datascientest-fastAPI-project-group-25/fastAPI-project-release
    targetRevision: main
    path: charts/fastapi
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
