server:
  service:
    type: LoadBalancer
  ingress:
    enabled: true

  extraArgs:
    - --insecure

configs:
  cm:
    application.instanceLabelKey: argocd.argoproj.io/instance
    kustomize.buildOptions: "--enable-helm"
    repositories: |
      - url: https://github.com/datascientest-fastAPI-project-group-25/fastAPI-project-release

  # Let ArgoCD generate a random initial admin password
  # We'll retrieve it after installation using:
  # kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d

  params:
    server.insecure: true

rbac:
  policy.default: role:readonly
  policy.csv: |
    g, system:authenticated, role:admin
