server:
  service:
    type: LoadBalancer
  ingress:
    enabled: true

  extraArgs:
    - --insecure

configs:
  cm:
    application.instanceLabelKey: argocd.argoproj.io/instance
    kustomize.buildOptions: "--enable-helm"
    repositories: |
      - url: https://github.com/datascientest-fastAPI-project-group-25/fastAPI-project-release

  # Remove secret section to use the default admin password
  # secret:
  #   argocdServerAdminPassword: admin123

  params:
    server.insecure: true

rbac:
  policy.default: role:readonly
  policy.csv: |
    g, system:authenticated, role:admin
