aws_region = "us-east-1"
aws_account_id = "221082192409"
environment = "prod"
project_name = "fastapi-project"
vpc_cidr = "10.2.0.0/16"
allowed_cidr_blocks = ["0.0.0.0/0"]
eks_cluster_version = "1.27"
eks_node_group_instance_types = ["t3.medium"]
eks_node_group_desired_size = 3
eks_node_group_min_size = 2
eks_node_group_max_size = 6
github_username = "${{ secrets.GITHUB_USERNAME }}"
github_token = "${{ secrets.GITHUB_TOKEN }}"
db_username = "${{ secrets.DB_USERNAME }}"
db_password = "${{ secrets.DB_PASSWORD }}"
db_name = "postgres"

github_org = "datascientest-fastapi-project-group-25"
release_repo = "fastAPI-project-release"
