# ================================
# Development Environment Provider Configuration
# ================================

# AWS provider configuration
provider "aws" {
  region = var.aws_region
}

# Data source to get EKS cluster information
data "aws_eks_cluster" "cluster" {
  name = "fastapi-project-eks-dev"
}

data "aws_eks_cluster_auth" "cluster" {
  name = "fastapi-project-eks-dev"
}

# Configure Kubernetes provider with EKS cluster details
provider "kubernetes" {
  insecure               = true # Allow insecure connections initially
  host                   = "https://localhost:8080" # Placeholder
  cluster_ca_certificate = base64decode("LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJMU1EUXhPREV3TkRneU5Gb1hEVE0xTURReE5URXdORGd5TkZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTXJuCnVxV0RvZzRGMnZPZHFCUEp1NFdnWWNrOEI5Y2huSGVMeGZmOUlteVJhV2d1ZU1lWm9nQ0FNRkpVR2Y5V0JWaysKWkQvVDRGRUVPOFJkNnBEK1Z1QXRnWVd4VnBGRnA0RjRpRWxOYUFxWWRMb3FNMlZuQzJ2NkJUOUJiN3lyRzNwRQpDZmNJWXBNcVJtbGFuMWhiOVQxcTlKcmZhbW5QZHNldEt0dkw2ekhJdWVQWnFKSGZPa2hqZXdRRGJEUEZiZFBzCnJiQlhpVlFzTVZ5ZnJrY0FXcEsrYTJkaHNrK0NvYmVXRzNrL1NVdEdmZGlMY3FmYXMzOEpQcGxpWWxOWnZVWEMKWWNXWGI0RGJwSkRQVzJDRlIzMVFwcGdNL0FXa0JMaGtJcGxkSXpZMFRGQ2NMRlRTamRFYkdEZnJsWnB2ZVdJNQpjbGRxK0VrVWZVTUNBd0VBQWFOQ01FQXdEZ1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93UUZNQU1CCkFmOHdIUVlEVlIwT0JCWUVGRWwxYnVBTU5yaXk2ZlBYZVJGK0hkSm9GRGhHTUEwR0NTcUdTSWIzRFFFQkN3VUEKQTRJQkFRQkVNZFJFNHcrS2FLbUxYaHQzOGdjYkVveGNYZFpwYnNlRDlNcnRpTnQyWWhyNWF1QTdsY2ZnUGZJYQpDcEFhSTJBdWU2UGNmZnZUM0dESUNiRGNEYnVjZ3ZYa1lKMXdNZjdwWWxTa0pKRmNXcTRwWkZFbWpwZFNXQXJnCnRWVXVkK0NYWWRjYmFLZnJtNlY2eHRIUGVNcDhNOVg1VkZQK1lnVnZIcVpzTXIwZmcvakVxYkJyVXBzYVpBbXgKUXdERGdNK0NRM05zYlpXbk9QcjZkQ3RwZnNhTVlYcGNXKzNJOFBCTWVLbFZPbnZRL0VtRnJYZzZMMHlGdjFRegpBcFRXamVtbXNxcGZ2THQyZUNlK2hpWTNHQlFuY1dCQnN3RGJlR3BKV0NBdFdIZ0tUVFkwVVNlUGN1RnF0K1VtCnRLVzJrUGdmYjkxRjZFZUVBZWJYWnhLbQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==") # Placeholder
  token                  = "placeholder-token"
}

# Configure Helm provider with EKS cluster details
provider "helm" {
  kubernetes {
    insecure               = true # Allow insecure connections initially
    host                   = "https://localhost:8080" # Placeholder
    cluster_ca_certificate = base64decode("LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJMU1EUXhPREV3TkRneU5Gb1hEVE0xTURReE5URXdORGd5TkZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTXJuCnVxV0RvZzRGMnZPZHFCUEp1NFdnWWNrOEI5Y2huSGVMeGZmOUlteVJhV2d1ZU1lWm9nQ0FNRkpVR2Y5V0JWaysKWkQvVDRGRUVPOFJkNnBEK1Z1QXRnWVd4VnBGRnA0RjRpRWxOYUFxWWRMb3FNMlZuQzJ2NkJUOUJiN3lyRzNwRQpDZmNJWXBNcVJtbGFuMWhiOVQxcTlKcmZhbW5QZHNldEt0dkw2ekhJdWVQWnFKSGZPa2hqZXdRRGJEUEZiZFBzCnJiQlhpVlFzTVZ5ZnJrY0FXcEsrYTJkaHNrK0NvYmVXRzNrL1NVdEdmZGlMY3FmYXMzOEpQcGxpWWxOWnZVWEMKWWNXWGI0RGJwSkRQVzJDRlIzMVFwcGdNL0FXa0JMaGtJcGxkSXpZMFRGQ2NMRlRTamRFYkdEZnJsWnB2ZVdJNQpjbGRxK0VrVWZVTUNBd0VBQWFOQ01FQXdEZ1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93UUZNQU1CCkFmOHdIUVlEVlIwT0JCWUVGRWwxYnVBTU5yaXk2ZlBYZVJGK0hkSm9GRGhHTUEwR0NTcUdTSWIzRFFFQkN3VUEKQTRJQkFRQkVNZFJFNHcrS2FLbUxYaHQzOGdjYkVveGNYZFpwYnNlRDlNcnRpTnQyWWhyNWF1QTdsY2ZnUGZJYQpDcEFhSTJBdWU2UGNmZnZUM0dESUNiRGNEYnVjZ3ZYa1lKMXdNZjdwWWxTa0pKRmNXcTRwWkZFbWpwZFNXQXJnCnRWVXVkK0NYWWRjYmFLZnJtNlY2eHRIUGVNcDhNOVg1VkZQK1lnVnZIcVpzTXIwZmcvakVxYkJyVXBzYVpBbXgKUXdERGdNK0NRM05zYlpXbk9QcjZkQ3RwZnNhTVlYcGNXKzNJOFBCTWVLbFZPbnZRL0VtRnJYZzZMMHlGdjFRegpBcFRXamVtbXNxcGZ2THQyZUNlK2hpWTNHQlFuY1dCQnN3RGJlR3BKV0NBdFdIZ0tUVFkwVVNlUGN1RnF0K1VtCnRLVzJrUGdmYjkxRjZFZUVBZWJYWnhLbQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==") # Placeholder
    token                  = "placeholder-token"
  }
}
