name: Terraform Validation

on:
  pull_request:
    branches: [ development, main ]
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform-validate.yml'

jobs:
  validate:
    name: Validate Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7
        
      - name: Terraform Format
        run: terraform fmt -check -recursive
        
      - name: Terraform Init
        run: |
          cd terraform
          terraform init -backend=false
        
      - name: Terraform Validate
        run: |
          cd terraform
          terraform validate
          
      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          working_directory: terraform
          
      - name: Run checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: terraform
          framework: terraform
          quiet: true
          soft_fail: false
