name: Terraform

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::575977136211:role/github-actions-dev
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: |
          cd terraform/environments/clean-deploy/development
          terraform init \
            -backend-config="bucket=fastapi-project-terraform-state-575977136211" \
            -backend-config="key=fastapi/infra/terraform.tfstate" \
            -backend-config="region=us-east-1" \
            -backend-config="dynamodb_table=terraform-state-lock-dev"

      - name: Terraform Format
        run: |
          cd terraform
          terraform fmt -check -recursive

      - name: Terraform Plan
        if: github.event_name == 'pull_request'
        run: |
          cd terraform/environments/clean-deploy/development
          terraform plan -var-file=terraform.tfvars

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          cd terraform/environments/clean-deploy/development
          terraform apply -var-file=terraform.tfvars -auto-approve
